import { extendZodWithOpenApi, OpenAPIRegistry } from '@asteasolutions/zod-to-openapi';
import { z } from 'zod';
extendZodWithOpenApi(z);
export const registry = new OpenAPIRegistry();
export const RoleSchema = z.enum(['admin', 'user']).openapi('Role');
export const UserStatusSchema = z.enum(['active', 'inactive']).openapi('UserStatus');
export const TicketStatusSchema = z.enum(['todo', 'in_progress', 'review', 'blocked', 'done']).openapi('TicketStatus');
export const PrioritySchema = z.enum(['low', 'medium', 'high']).openapi('Priority');
export const LabelColorSchema = z.enum(['secondary-container', 'primary-fixed', 'tertiary-fixed', 'surface-container-highest']).openapi('LabelColor');
export const UserSchema = registry.register('User', z.object({ id: z.string().uuid(), username: z.string(), name: z.string(), email: z.string().email(), role: RoleSchema, status: UserStatusSchema, avatarUrl: z.string().nullable(), createdAt: z.string().datetime(), updatedAt: z.string().datetime() }));
export const UserSummarySchema = registry.register('UserSummary', UserSchema.pick({ id: true, username: true, name: true, email: true, status: true, avatarUrl: true }));
export const LabelSchema = registry.register('Label', z.object({ id: z.string().uuid(), name: z.string(), color: LabelColorSchema }));
export const TicketSchema = registry.register('Ticket', z.object({ id: z.string().uuid(), key: z.string(), title: z.string(), description: z.string(), status: TicketStatusSchema, priority: PrioritySchema, labels: z.array(LabelSchema), creator: UserSummarySchema.nullable(), assignee: UserSummarySchema.nullable(), createdAt: z.string().datetime().nullable(), updatedAt: z.string().datetime().nullable(), closedAt: z.string().datetime().nullable(), archivedAt: z.string().datetime().nullable(), position: z.number().int(), version: z.number().int() }));
export const ErrorSchema = registry.register('ApiError', z.object({ code: z.string(), message: z.string(), details: z.unknown().optional() }));
export const ErrorEnvelopeSchema = registry.register('ErrorEnvelope', z.object({ data: z.null(), error: ErrorSchema }));
export const TicketLockSchema = registry.register('TicketLock', z.object({ ticketId: z.string().uuid(), lockedBy: UserSummarySchema, lockedAt: z.string().datetime(), expiresAt: z.string().datetime() }));
export const AuditLogSchema = registry.register('AuditLog', z.object({ id: z.string().uuid(), ticketId: z.string().uuid(), actor: UserSummarySchema.nullable(), action: z.string(), field: z.string().nullable(), oldValue: z.string().nullable(), newValue: z.string().nullable(), createdAt: z.string().datetime() }));
export const LoginSchema = registry.register('LoginPayload', z.object({ email: z.string().email(), password: z.string().min(1) }));
export const TicketListQuerySchema = z.object({ search: z.string().optional(), status: TicketStatusSchema.optional(), priority: PrioritySchema.optional(), assigneeId: z.string().uuid().optional(), creatorId: z.string().uuid().optional(), labelId: z.string().uuid().optional(), archived: z.coerce.boolean().optional().default(false), limit: z.coerce.number().int().min(1).max(100).optional().default(50), offset: z.coerce.number().int().min(0).optional().default(0) });
export const CreateTicketSchema = registry.register('CreateTicketPayload', z.object({ title: z.string().trim().min(1).max(240), description: z.string().trim().min(1), priority: PrioritySchema, assigneeId: z.string().uuid().nullable().optional(), labelIds: z.array(z.string().uuid()).optional().default([]) }));
export const UpdateTicketSchema = registry.register('UpdateTicketPayload', z.object({ title: z.string().trim().min(1).max(240).optional(), description: z.string().trim().min(1).optional(), priority: PrioritySchema.optional(), status: TicketStatusSchema.optional(), assigneeId: z.string().uuid().nullable().optional(), labelIds: z.array(z.string().uuid()).optional(), version: z.number().int().min(1) }));
export const ChangeStatusSchema = registry.register('ChangeStatusPayload', z.object({ status: TicketStatusSchema, version: z.number().int().min(1) }));
export const ChangePositionSchema = registry.register('ChangePositionPayload', z.object({ status: TicketStatusSchema, position: z.number().int().min(0), version: z.number().int().min(1) }));
export const VersionPayloadSchema = registry.register('VersionPayload', z.object({ version: z.number().int().min(1) }));
export const LockTicketSchema = registry.register('LockTicketPayload', z.object({ timeoutSeconds: z.number().int().min(30).max(3600).optional().default(300) }));
export const success = <T extends z.ZodTypeAny>(name: string, dataSchema: T) => registry.register(name, z.object({ data: dataSchema, error: z.null() }));
export const UserEnvelopeSchema = success('UserEnvelope', z.object({ user: UserSchema.nullable() }));
export const TicketEnvelopeSchema = success('TicketEnvelope', z.object({ ticket: TicketSchema }));
export const TicketListEnvelopeSchema = success('TicketListEnvelope', z.object({ items: z.array(TicketSchema), total: z.number().int(), limit: z.number().int(), offset: z.number().int() }));
export const TicketLockEnvelopeSchema = success('TicketLockEnvelope', z.object({ lock: TicketLockSchema }));
export const AuditLogListEnvelopeSchema = success('AuditLogListEnvelope', z.object({ items: z.array(AuditLogSchema), total: z.number().int(), limit: z.number().int(), offset: z.number().int() }));
